name: Test Skript Scripts
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
      - uses: Andromedov/skript-tests-action@v1.0
        with:
          minecraft-version: '1.21.11'
          skript-version: '2.15.2'
          path-to-skripts: './Skript'
          path-to-addons: './addons'
          server-software: 'paper'